#!/usr/bin/env bash

# load all scripts under .bash.d
shopt -s nullglob
for script in ~/.bash.d/*.sh; do
    source "$script"
done

for script in ~/.bash.d_local/*.sh; do
    source "$script"
done    
    
unset -v script
